# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'godot_plugin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for godot_plugin
  pod 'Google-Mobile-Ads-SDK'

end
